import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mexiko Reise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mexiko Reise
        </h1>

        <p className={styles.description}>
          Hier findest du eine Liste mit allen Dingen, die du in Mexiko machen kannst.
        </p>
        <p className={styles.hinweisePink}>
        Ich empfehle euch, diese Orte zu besuchen. Sie decken alle wichtigen Bereiche des CDMX ab: historisch und modern. 
        Einige der Stadtteile sind: <strong className={styles.span}>Centro Histórico (Altstadt), Roma Norte, Condesa, Polanco, Coyoacán, Xochimilco.</strong>
        </p>

        <div className={styles.grid}>
          <Link href="/blog/sehenswurdigkeiten">
            <a className={styles.card}>
              <h2>Sehenswurdigkeiten &rarr;</h2>
              <Image src="/bellas-artes.jpg" alt="Bellas Artes" height={200} width={200} />
              <p>Die besten Orte von CDMX</p>
            </a>
          </Link>

          <Link href="/blog/essen">
            <a className={styles.card}>
              <h2>Essen &rarr;</h2>
              <Image src="/comida-mexico.jpg" alt="mexikanisches Essen" height={200} width={200} />
              <p>Leckeres Essen!</p>
            </a>
          </Link>          

        </div>
      </main>

      <footer className={styles.footer}>
        <p>Gandhi Hernandez</p>
      </footer>
    </div>
  )
}
